export default function() {
  const result = {
    code: '0',
    message: '请求成功',
    data: {
      current: 1,
      size: 20,
      total: 7,
      list: [
        {
          checkingRecordId: 33,
          lessonId: 24,
          courseType: 1,
          courseSubType: 2,
          teachType: 2,
          students: [
            {
              student: {
                id: 113,
                unionid: '082c05f2dd1549de91e79b0f9fca5651',
                name: '赵贝贝测407',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: { id: 5, name: '督导' },
              absence: false,
            },
            {
              student: {
                id: 136,
                unionid: '7548b40c3d7a4c18b5c77f9423ccfd76',
                name: '赵贝贝测808',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: { id: 5, name: '督导' },
              absence: false,
            },
          ],
          studentNum: 2,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 3, name: '赵贝贝' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-28 08:00:00',
          endTime: '2024-07-13 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-25 14:27:12',
          financeCheckers: [{ id: 3, name: '赵贝贝' }],
          financeCheckStatus: 2,
          financeCheckTime: '2024-07-04 18:38:34',
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: 1,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 31,
          lessonId: 23,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 136,
                unionid: '7548b40c3d7a4c18b5c77f9423ccfd76',
                name: '赵贝贝测808',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: { id: 5, name: '督导' },
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 21, name: '默认值' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-01 08:00:00',
          endTime: '2024-07-01 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-25 14:26:08',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 29,
          lessonId: 22,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 136,
                unionid: '7548b40c3d7a4c18b5c77f9423ccfd76',
                name: '赵贝贝测808',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: { id: 5, name: '督导' },
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 21, name: '默认值' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-12 08:00:00',
          endTime: '2024-07-12 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-25 14:25:56',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 27,
          lessonId: 20,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 136,
                unionid: '7548b40c3d7a4c18b5c77f9423ccfd76',
                name: '赵贝贝测808',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: null,
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 21, name: '默认值' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-15 08:00:00',
          endTime: '2024-07-15 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-25 14:07:35',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 15,
          lessonId: 16,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 19,
                unionid: '497f9bb3f664463f93bb4f08da674124',
                name: '赵贝贝测959',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: { id: 5, name: '督导' },
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 3, name: '赵贝贝' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-15 11:10:00',
          endTime: '2024-07-21 11:12:00',
          patched: false,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10046, name: '兼职教师' },
          confirmTime: '2024-07-21 11:16:15',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 9,
          lessonId: 9,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 7,
                unionid: 'ff7a602c44384b87a18076b89578383d',
                name: '赵贝贝测369',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: null,
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 4, name: '全职教师' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-07 03:00:00',
          endTime: '2024-07-07 05:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-11 22:00:27',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 3,
          lessonId: 4,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 7,
                unionid: 'ff7a602c44384b87a18076b89578383d',
                name: '赵贝贝测369',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: null,
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 4, name: '全职教师' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-07-05 08:00:00',
          endTime: '2024-07-05 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-10 22:52:26',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 3,
          lessonId: 111,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 7,
                unionid: 'ff7a602c44384b87a18076b89578383d',
                name: '赵贝贝测369',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: null,
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 4, name: '全职教师' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-08-05 08:00:00',
          endTime: '2024-07-05 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-10 22:52:26',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
        {
          checkingRecordId: 3,
          lessonId: 2222,
          courseType: 1,
          courseSubType: 2,
          teachType: 1,
          students: [
            {
              student: {
                id: 7,
                unionid: 'ff7a602c44384b87a18076b89578383d',
                name: '赵贝贝测369',
              },
              schoolGroup: 10,
              grade: 21,
              studyManager: { id: 3, name: '赵贝贝' },
              supervisor: null,
              absence: false,
            },
          ],
          studentNum: 1,
          absenceNum: 0,
          grades: [21],
          teacher: { id: 4, name: '全职教师' },
          classSupervisor: null,
          subject: 11,
          startTime: '2024-09-05 08:00:00',
          endTime: '2024-07-05 10:00:00',
          patched: true,
          teamClass: null,
          courseProduct: { id: 2, name: '青藤花开2024沧州地区课程' },
          teachSchool: { id: 21, name: '天津武清万博广场校区' },
          teachSchoolGroup: 0,
          confirmor: { id: 3, name: '赵贝贝' },
          confirmorPosition: { code: 10044, name: '学管师' },
          confirmTime: '2024-07-10 22:52:26',
          financeCheckers: null,
          financeCheckStatus: 1,
          financeCheckTime: null,
          studyManagerCheckers: null,
          studyManagerCheckStatus: 1,
          studyManagerCheckTime: null,
          finalCheckStatus: null,
          finalCheckTime: null,
          checkTime: null,
          refuseReason: '',
          refuseOperator: null,
          classtimeFiles: [],
        },
      ],
    },
    timestamp: '2024-07-13 22:43:44',
  };

  return result;
}
